### ISSUE TITLE
PlanningPhase -> Section "Move to AnalysisPhase"

### ISSUE THREAD

**Issue by daguag** [blochberger/developer-guidelines#14]
Abschnitte #sensitive data und #indiviudal with special need for protection: Wäre das sinnvoll in einen definitorischen Abschnitt in die Introduction zu packen? Oder gar eine Art Glossar?

Abschnitt "#### Extend of data used" verstehe ich nicht ganz, findet sich das in der aktualisierten Version von "AnalysisPhase" vielleicht schon wieder?

**Comment by blochberger** [comment]
Is this fixed by 3e4264ce2db086a9799c734d8e29fca3e7ab4f8e?

**Comment by daguag** [comment]
I think so :)
