### ISSUE TITLE
Separation of Implementation and Testing Phase

### ISSUE THREAD

**Issue by blochberger** [blochberger/developer-guidelines#22]
https://github.com/blochberger/developer-guidelines/blob/e7d33026e95d2657212fe01c511a8106e35147d4/ImplementationPhase.md#L1

I think the title is a bit confusing, as we already have a [Testing Phase](https://github.com/blochberger/developer-guidelines/blob/e7d33026e95d2657212fe01c511a8106e35147d4/TestingPhase.md) section.

**Comment by daguag** [comment]
I removed the word testing here. Think this resolves the issue for now.
